### ISSUE TITLE
Is there way to use this approach with client hosted STS server?

### ISSUE THREAD

**Issue by albertoconnor** [AzureAD/azure-activedirectory-library-for-python#1]
I am working on a Dynamics CRM integration for a client. I wasn't involved in the setup of the CRM but from poking around they seem to have their own sts server setup at

`https://sts.orgname.org/`

And I can access the normal login page at `https://sts.orgname.org/adsf/ls/`.

If I use `https://sts.orgname.org/` as the `AUTHORIZATION_URL` I get the error

`Authority: ERROR: Instance Discovery request failed`

I get this error no matter if I include `/adsf/ls/` or not. Is there an magic `AUTHORIZATION_URL` equivalent I can derive from `https://sts.orgname.org`?

I can definitely provide more information and context if it is required. There maybe documentation which addresses this question but it has proved challenging to find.

**Comment by MarkDordoy-JustEat** [comment]
+1

**Comment by yugangw-msft** [comment]
@MarkDordoy-JustEat @albertoconnor, 
Likely similar fix is needed like what was done on [adal-node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/121). Let me know if you are willing to verify by installing it from my branch, before it gets released out

**Comment by yugangw-msft** [comment]
I will fix it. 
The authority should be `https://sts.orgname.org/adfs`.
The discovery should be skipped for adfs server, so the error of `Instance Discovery request failed` should not occur.

**Comment by yugangw-msft** [comment]
fixed in 0.4
