### ISSUE TITLE
Is the v2 endpoint currently supported?

### ISSUE THREAD

**Issue by Preston-Landers** [AzureAD/azure-activedirectory-library-for-python#100]
As far as I can tell this isn't mentioned in the docs and it is not supported. 

The endpoints seem to be hardcoded to `/oauth2/token`. I tried replacing them but then ADAL tries to send the `resource` parameter when calling `acquire_token_with_authorization_code` and it fails with:

AADSTS90100: The 'resource' request parameter is not supported.

I was hoping to use the v2 endpoint to gain access to the incremental consent and other features but it looks like I can't for now. Thanks.

**Comment by Preston-Landers** [comment]
By the way, I see now that despite the endpoint being "hardcoded", you can set the api_version kwarg and it uses that in the URL. However, the problem with it adding the `resource` still stands.

Is anyone actively working on v2 support? If not I may try to tackle it.

**Comment by Preston-Landers** [comment]
Actually I got it working. I'll add more information tomorrow.

**Comment by Preston-Landers** [comment]
Here's a summary of the changes I had to make in my app to make it work with the Azure 2.0 endpoint.

* In calls to adal.AuthenticationContext, give the `api_version='2.0'` parameter.
* The `resource` parameter should be blank in adal calls
* Instead of adding a `resource` parameter, put resource-scoped permissions in the `scope` param to the `/authorize` request.
* The /authorize request also needs the 2.0 endpoint in the URL (or as a form param?)
* Scope may also need `openid`, `email`, `profile`, and `offline_access` depending on your app's needs.
* Be sure to set `response_type` correctly depending on if you need an access token (`code`), `id_token`, or both.
* You can't inspect the access tokens - they are opaque. 
* Be prepared to deal with some minor differences in the keys  in the identity token.
* When fetching the `/.well-known/openid-configuration` be sure to incorporate the correct tenant ID and endpoint version in the URL or you can get the wrong key.

These links may also help:

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-limitations

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-preview-oidc-changes

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-flows

**Comment by Preston-Landers** [comment]
Reopening because I'm curious about something else pertaining to this.

In my web app, I normally have a web-based flow where to connect to Azure AD, my server redirects the user to the /authorize URL on the endpoint, and when v2 endpoint is active, I include the scope= parameter. When processing the callback, I call adal's `acquire_token_with_authorization_code` to turn this into a usable token for Graph API requests. As long as I follow the rules I mentioned above this works with the v2 endpoint.

Now I want to support a slightly different scenario that is a direct server-to-server communication not involving a specific end user account. My goal is to have a "Test Azure connection" button that admins can run to ensure that they have valid settings for the AAD App ID, tenants, and client secret. I want them to be able to run this without signing in to an Azure account since they're verifying a direct server-to-server connection.

Instead of redirecting the web user, the server code just directly calls adal's `acquire_token_with_client_credentials` using the AAD Graph resource ID and this seems to work fine with ADAL in the v1 endpoint.

According to the V2 endpoint docs here under "Get a token":

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds

The v2 process is basically the same except I set the `scope` parameter instead of the `resource` one. Unfortunately ADAL.py doesn't seem to allow for a way to do that. My request results in:

AADSTS90014: The required field 'scope' is missing.

I could construct the `/token` URL and run the request myself but I was hoping to keep that kind of logic in ADAL. It would be nice if `acquire_token_with_client_credentials` and related methods had a way to pass in the scope with a keyword argument.

**Comment by Preston-Landers** [comment]
This isn't a complete PR, but this change seems to allow me to do what I want:

https://github.com/AzureAD/azure-activedirectory-library-for-python/compare/dev...Preston-Landers:issue-100-scope?expand=1

**Comment by navyasric** [comment]
@Preston-Landers Thank you for your interest in the library. Currently, there is no support for v2 endpoint in ADAL Python as you have already discovered. We are evaluating plans for providing client library support for v2 endpoint and will update once they are concrete.

**Comment by nomius** [comment]
> @Preston-Landers Thank you for your interest in the library. Currently, there is no support for v2 endpoint in ADAL Python as you have already discovered. We are evaluating plans for providing client library support for v2 endpoint and will update once they are concrete.

Hi,
  What's the status of this?

 Thanks in advance!

**Comment by rayluo** [comment]
@Preston-Landers @PlugaruT @nomius @mathgrondin @freeek3
There is no plan to add v2 endpoint support in ADAL Python. But there is a preview version of [MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python) supports v2 endpoint.
