### ISSUE TITLE
Please add the support for MFA.  

### ISSUE THREAD

**Issue by rohrerb** [AzureAD/azure-activedirectory-library-for-python#101]
Please add support for MFA to allow customers to automate deployments of MFA.  At the moment,  it seems Microsoft only supports MFA automation via Powershell.

https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/6998686-update-the-azure-active-directory-powershell-modul
http://connect.microsoft.com/site1164/content/content.aspx?ContentID=32016

**Comment by navyasric** [comment]
@rohrerb Can you please provide details about your app and its use case? How do you propose to use ADAL for your app?

**Comment by rohrerb** [comment]
The use case is the same as users who want to automate/script out this process using PS.  Not all users have the capability to use powershell (MAC or Linux users).   Please support mfa automation/scripting through other languages such as python.

**Comment by rayluo** [comment]
Hey @rohrerb , does the comments in the other issue [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/116#issuecomment-370096629) help?

**Comment by mattxbart** [comment]
I'm running into the same issue. I want to use the graph api to execute a script but since MFA doesn't work I have to use an app permission instead of delegating through my user. I would really like to see MFA support or a suggestion on how to do this without using web based interactions.

**Comment by rayluo** [comment]
@mattxbart To make sure we are on the same page, what API call was your script trying to use? Was it [acquire_token_with_username_password(...)](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.0.2/adal/authentication_context.py#L147) or something else?

Also, what is your expectation of "MFA support"? If you mean a fully-automation that totally bypass MFA, that is probably what MFA was trying to prevent. If you mean to trigger an interactive flow for end user to complete MFA, which can considered as semi-automation, it would rely on web based interaction under the hood.

Nonetheless, if you can use app permission to avoid an end user role, that is probably the better way to go. Conceptually speaking, when your app does not need to impersonate an end user, it can then do lots of things, automatically.

**Comment by mattxbart** [comment]
Yes @rayluo, I'm trying to use acquire_token_with_username_password. I was expecting it to prompt for the MFA code but it threw an error message about a problem with MFA. I can use the app permission, it just didn't seem as secure as using an MFA enabled method but I will do that now. Thanks!

**Comment by Preston-Landers** [comment]
@mattxbart Is your application a web app? If so you can use `acquire_token_with_authorization_code` with users who must sign in with MFA.

**Comment by dimuthulakshan** [comment]
@Preston-Landers I am using` acquire_token_with_authorization_code `  `with code_verifier='PKCE'`, Still it didn't pop up MFA for user login. Are there any other configuration in python? 

`token_response = auth_context.acquire_token_with_authorization_code(code, REDIRECT_URI, azure_config.RESOURCE,
                                                                        azure_config.CLIENT_ID, azure_config.CLIENT_SECRET, 'PKCE')`

Appreciate your support, Thanks

**Comment by rayluo** [comment]
@dimuthulakshan The PKCE thing is not relevant in MFA topic. Just follow @Preston-Landers 's hint to use `acquire_token_with_authorzation_code()` in the [normal way](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.1/sample/website_sample.py#L113), and then the MFA - if required - would be triggered by service side and be completed inside the browser.

**Comment by rayluo** [comment]
At this point, the [ADAL Python library will not receive new features](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/README.md). Its successor, [MSAL Python, is generally available](https://developer.microsoft.com/en-us/office/blogs/microsoft-authentication-libraries-for-java-and-python-are-now-generally-available/), and will soon release the [`acquire_token_interactive()` behavior](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/260) for desktop app, and the [`initiate_auth_code_flow()` & `acquire_token_by_auth_code_flow()` for web app](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/276). You folks can give it a shot.

**Comment by rayluo** [comment]
Implemented in MSAL Python 1.7+. Please switch to MSAL Python.
