### ISSUE TITLE
Authenticate with Managed Service Identity

### ISSUE THREAD

**Issue by twschiller** [AzureAD/azure-activedirectory-library-for-python#108]
We're looking to authenticate an App Service to the other Azure APIs (e.g. Key Vault). Is it possible to use the AADL library with the new Managed Service Identities feature?
https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity

It looks like it's probably not available yet? https://docs.microsoft.com/en-us/azure/active-directory/msi-known-issues#does-msi-work-with-the-active-directory-authentication-library-adal-or-the-microsoft-authentication-library-msal

**Comment by navyasric** [comment]
That's correct. It is currently not available in ADAL. We may plan to support it in the future based on the demand.
