### ISSUE TITLE
Missing ADAL tutorial

### ISSUE THREAD

**Issue by patchie** [AzureAD/azure-activedirectory-library-for-python#109]
How should a average Python programmer be able to easily take use of ADAL library without any tutorials?

Please give us a step by step tutorial.

**Comment by navyasric** [comment]
Thank you for the feedback. We have added a work item to our backlog to produce a tutorial and will update here when it is ready.

**Comment by rayluo** [comment]
This will be an ongoing effort. Right now the (first) baby step you can find is this wiki page on [Register your application with Azure Active Directory](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Register-your-application-with-Azure-Active-Directory) and we are [including that link into samples](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/132).

**Comment by navyasric** [comment]
@patchie You can now find a sample with detailed steps for ADAL Python here: https://github.com/Azure-Samples/active-directory-python-webapp-graphapi

This is also linked from our [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-developers-guide). 
Closing this issue.
