### ISSUE TITLE
Data does not contain values

### ISSUE THREAD

**Issue by usama-masood** [AzureAD/azure-activedirectory-library-for-python#115]
By this library I am able to fetch access token via client credentials method. 

When I am using that token to fetch data from APIM wrapper, the result responded with "status 200" OK but inside content it has "no values". The same resource responds with plenty of data when called from postman.

**Comment by usama-masood** [comment]
if I use access token generated by postman or developer portal in python code manually, the request returns with data too. Means there is some problem with fetched token.

This code i am using for token access:
context = adal.AuthenticationContext(
    AUTHORITY_URL, validate_authority='fcb8a5b2-79a9-497c-929a-b2cc1a894575' != 'adfs',
    api_version=None)
token = context.acquire_token_with_client_credentials(
    RESOURCE_URI,
    CLIENT_ID,
    CLIENT_SECRET)
access_token = token.get('accessToken')

How it is providing me an access token which when passed into API call returns with status 200 OK but no data.

**Comment by rayluo** [comment]
Your code snippet above looks OK. How exactly did you get the token the other way, then? We might be able to find some discrepency, if any, in those parameters.

**Comment by usama-masood** [comment]
Thank you for responding. 
Issue got resolved. The problem was from APIM end. Application registered in AAD to access APIM was not assigned all permissions to access . Due to un-authorization, APIM was not returning data. 
There might be some bug because it must return with un-authorized 401 with detailed exception message whereas it was returning with status OK 200 . May be Microsoft team would fix this ambigous response later.

**Comment by rayluo** [comment]
Good to know. Feel free to contact APIM for the 200 vs 401 topic.
