### ISSUE TITLE
how to develop for Multi-Factor Authentication 

### ISSUE THREAD

**Issue by michaelllh** [AzureAD/azure-activedirectory-library-for-python#116]
how to develop for Multi-Factor Authentication , I can not find any development document in offical website , so I want to ask whether microsoft offer some technical document to develop for Multi-Factor Authentication account?

**Comment by victoirj** [comment]
same problem. I cannot disable MFA, but none of the documentation found that explains how to achieve this

**Comment by rayluo** [comment]
The [authorization code flow example](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/website_sample.py) and [device code flow example](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/device_code_sample.py) both work with MFA. Will that work for you? You can also contact our PM @navyasric for more info about documentation.

**Comment by navyasric** [comment]
@victoirj Can you provide more details about your scenario's expectation? Are you encountering an error and want to handle the MFA requirements during authentication in your app?

**Comment by rayluo** [comment]
Closing this issue as the [previous answer](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/116#issuecomment-370096629) still holds.

But if you are starting your new project today, and want to follow those samples, you might as well start afresh with [MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python) which has the SAME by-design MFA behavior, but with more polished samples.

**Comment by rayluo** [comment]
See also [this comment](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/101#issuecomment-737747541)
