### ISSUE TITLE
Use DEBUG level for detailed logging

### ISSUE THREAD

**Issue by letmaik** [AzureAD/azure-activedirectory-library-for-python#122]
This library currently uses INFO level for some log messages which I would consider DEBUG level like below. This produces a lot of noise when setting the root logger to INFO in an application. I would suggest that for the messages below the DEBUG level is used.

```
18:39:54 adal-python      140073437169408 INFO  706dfbee-36cf... - TokenRequest:Getting token from cache with refresh if necessary.
18:39:54 adal-python      140073437169408 INFO  9a95f211-4224... - TokenRequest:Acquiring token with username password.
18:39:54 adal-python      140073437169408 INFO  9a95f211-4224... - UserRealm:User Realm Discovery Server returned this correlation_id: 9a95f211-4224...
18:39:55 adal-python      140073437169408 INFO  9a95f211-4224... - WSTrustRequest:WS-Trust RST Server returned this correlation_id: 9a95f211-4224...
18:39:55 adal-python      140073437169408 INFO  9a95f211-4224... - WSTrustResponse:Found token of type: urn:oasis:names:tc:SAML:1.0:assertion
18:39:56 adal-python      140073437169408 INFO  9a95f211-4224... - OAuth2Client:Get Token Server returned this correlation_id: 9a95f211-4224...
```

**Comment by Cloudenius** [comment]
Thanks for raising this issue @letmaik. @rayluo, any idea when this can be fixed? Thanks!

**Comment by imatiach-msft** [comment]
seeing this issue on my machine as well, seems really annoying to see all of the INFO debug statements

**Comment by rayluo** [comment]
Thanks folks in this thread (and @markmabe in @Cloudenius 's PR) for upvoting this!

We've been looking into this recently <sub>and doing some [head-banging experiments](https://stackoverflow.com/a/55623870/728675)</sub>. We will probably still get @Cloudenius 's PR #197 merged, but on the other hand, there is supposed to be a more elegant way of coordinating logs emitting from different imported library, WITHOUT needing to change those libraries's source code. Without further ado, would any of you try this and see if it can also be a feasible workaround even without @Cloudenius 's PR?

    import logging
    logging.getLogger("adal-python").setLevel(logging.WARN)  # Disables ADAL INFO & DEBUG logs

**Comment by markmabe** [comment]
@rayluo Thanks Ray, that is a good workaround for us.  👍

**Comment by rayluo** [comment]
Thanks @markmabe for the quick confirmation! For the record, that "workaround" is conceptually the canonical/standard way in Python to turn on/off underlying library's logging. Now we also document it in our [wiki page](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Logging).
