### ISSUE TITLE
Proxy information while authenticating

### ISSUE THREAD

**Issue by ImranBijapuri** [AzureAD/azure-activedirectory-library-for-python#135]
I am trying to obtain an access token with client credentials. 
I am trying to figure out how to pass the proxy information.

This is the code I am using
```
context = adal.AuthenticationContext(authority_url)
token = context.acquire_token_with_client_credentials(resource, client_id, client_secret)
print(token['accessToken'])
```

**Comment by rayluo** [comment]
Not hearing back. Closing for now. Feel free to reopen if you have follow-up questions.
