### ISSUE TITLE
Question: Service Principal creation

### ISSUE THREAD

**Issue by jorgecotillo** [AzureAD/azure-activedirectory-library-for-python#144]
Hello, this is a question not actually an issue but can anyone show/point me on how I can create an AD service principal?

Perhaps is something in the pipeline and not implemented yet?

Please, let me know.

Thanks!

**Comment by danieldobalian** [comment]
Service Principals are automatically created in a tenant the first time a user signs in and consents to a new Application.  

You can also programmatically create Service Principals via the [Microsoft Graph API](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/serviceprincipal).

**Comment by rayluo** [comment]
You may also find the following documentation useful:

* Our wiki page [Register your application with Azure Active Directory](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/Register-your-application-with-Azure-Active-Directory)
* Which links to [Integrating applications with Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications)
* Which also links to another conceptual document [Application and service principal objects in Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-application-objects)

**Comment by navyasric** [comment]
@jorgecotillo Closing this issue as it seems answered. Please reopen if you see it again.
