### ISSUE TITLE
Issues installing adal on python2.7

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/azure-activedirectory-library-for-python#145]
Whenever I attempt a `pip install adal`, I get the following error:

```
Collecting adal
  Could not fetch URL https://pypi.python.org/simple/adal/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
```

I've tried on 2 separate Unix machines (macOS) and it failed w/ the same error. Both machines were able to install using `pip3`.

**Comment by rayluo** [comment]
I tested it with Python 2.7.12 and pip 10.0.1 and 9.0.1, they all work on a git bash environment on my Windows laptop.

I think [this SO answer](https://stackoverflow.com/a/49748494) would probably help you.

> What's happening: Python.org sites are stopping support for TLS versions 1.0 and 1.1. This means that Mac OSX version 10.12 or older will not be able to use pip unless they upgrade pip as above.

**Comment by rayluo** [comment]
Hopefully the previous answer works. Let us know if you have questions. :-)
