### ISSUE TITLE
Auth always failed with resouces not listed in the requested permissions

### ISSUE THREAD

**Issue by jamesongit** [AzureAD/azure-activedirectory-library-for-python#146]
Hi,

I have the following python code:

```python
authority_host_uri = 'https://login.microsoftonline.com'
tenant = '<tenant id>'
authority_uri = authority_host_uri + '/' + tenant
resource_uri = 'https://management.core.windows.net/'
client_id = '<client id>'

context = adal.AuthenticationContext(authority_uri, api_version=None)
code = context.acquire_user_code(resource_uri, client_id)
print(code['message'])
mgmt_token = context.acquire_token_with_device_code(resource_uri, code, client_id)
```

and after entered the code in devicelogin page and select my corp account, it always fails with the following error:

> **Sorry, but we’re having trouble signing you in.
AADSTS65005: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: <client id>. Resource value from request: https://management.core.windows.net/. Resource app ID: 797f4846-ba00-4fd7-ba43-dac1f8f63013. List of valid resources from app registration: 00000002-0000-0000-c000-000000000000, 5148a6f0-cb72-4c3c-bc1d-07e24fa3ee95.**

What required permissions does the app need? I checked the AAD settings of my app, it already has 

![image](https://user-images.githubusercontent.com/7584263/40037586-ee80b63a-57c2-11e8-85bb-a0b640508b06.png)

**Comment by navyasric** [comment]
@jamesongit Closing this issue as it seems to be answered by above comment. Please reopen if you need to.
