### ISSUE TITLE
Need to relax the authority format check on trailing slash

### ISSUE THREAD

**Issue by rayluo** [AzureAD/azure-activedirectory-library-for-python#156]
In ADAL Python 0.7.0 and 1.0.0 we introduced a format check to ensure the authority input has the form of `https://some.host.name/tenant`. It successfully addresses #126, but it accidentally breaks existing customers who is using `https://some.host.name/tenant/` (i.e. with a trailing slash), such as [this one](https://github.com/Azure/azure-kusto-python/blob/3e6df299f86a65a0d5fe90b73cb133f7d75b0577/azure-kusto-data/azure/kusto/data/aad_helper.py#L11).

**Comment by stcheng** [comment]
thanks for logging this issue!

**Comment by stcheng** [comment]
one example would be: https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/azure/kusto/data/aad_helper.py#L11

**Comment by rayluo** [comment]
This issue has been addressed in the aforementioned PR and its subsequent release. Closing now.

PS: This issue was supposed to be auto-closed by PR #157 but we did not correctly cast [the spell](https://help.github.com/articles/closing-issues-using-keywords/) (pun intended). :-)
