### ISSUE TITLE
Proper way to validate the id_token

### ISSUE THREAD

**Issue by dwaltrip** [AzureAD/azure-activedirectory-library-for-python#172]
Hello! Thanks for creating this library to help python applications implement SSO with Azure AD.

For my python web app, I am looking to implement an OpenID Connect authentication flow, using the v1 Azure AD endpoint.

I have been using the following example code:
https://github.com/Azure-Samples/active-directory-python-webapp-graphapi

As well as the following guide:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#validate-the-idtoken

When the user attempts to login, I redirect them to the authorization URL:
```
https://login.microsoftonline.com/<tenant name>/oauth2/authorize?
    response_type=id_token+code
    &client_id=<my app's client id>
    &redirect_uri=my_app.com/oauth
    &state=<generated by my app> 
    &scope=openid
    &nonce=<secure nonce randomly generated by my app>
    &response_mode=form_post
```

After they successfully authenticate on the Microsoft login page, a `POST` request is then made to the `redirect_uri` for my application. I have successfully received an `id_token` as form data in this request.

However, I couldn't find any method provided by `adal`  that verifies the signature of the `id_token` -- as the documentation describes one should do to ensure they are receiving a valid token. Of course, the app must also ensure that the nonce value found in the `id_token` payload matches what was previously generated in the beginning of the flow.

I did find a stackoverflow answer that described a method for verifying the token signature: https://stackoverflow.com/a/43145184/111635. Does that method look correct?

What is the recommended approach for validating the `id_token` received by a python web app that is implementing the OpenID Connect authentication flow?

**Comment by dwaltrip** [comment]
Looks like the approach given in the stackoverflow answer above is correct.

`python-social-auth` and `django-azure-ad-auth` both use this approach as well (although the latter is fetching the keys used for signing in a different way):
* https://github.com/python-social-auth/social-core/blob/master/social_core/backends/azuread_tenant.py
* https://bitbucket.org/nextscreenlabs/django-azure-ad-auth/src/b16c538335230ffe31dd51e1f1821b7e112ada37/azure_ad_auth/utils.py?at=default&fileviewer=file-view-default

`python-social-auth` has a comment pointing to this blog post as well: https://nicksnettravels.builttoroam.com/post/2017/01/24/Verifying-Azure-Active-Directory-JWT-Tokens.aspx

**Comment by boykoc** [comment]
@rahulyaa Sorry to bug you, but would you be able to confirm that ADAL itself validates the `id_token`? I feel like it's happening around here https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/168292a44b3c6636dbf30c9d79249da01d6d1ada/adal/oauth2_client.py#L165

**Comment by rayluo** [comment]
ADAL Python decodes id_token and gets information from it, but historically ADAL Python does not validate an id_token in the JWT level<https://github.com/AzureAD/azure-activedirectory-library-for-python/blame/1.2.1/adal/oauth2_client.py#L133-L137>. That being said, ADAL Python already went extra mile to ensure we are talking to Microsoft Identity platform<https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.1/adal/authority.py#L49> in the first place, long before we send out the token request, so we are still reasonably confident that the response we obtain, and the tokens inside it, are legit.

________________________________

**Comment by boykoc** [comment]
@rayluo thank you for this response, I really appreciate you taking the time to share this information.

So, for a web application such as the samples in this [code base](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/60028fba619800559e74c929dd98aacbe249d392/sample/website_sample.py#L88) and the [graphapi one](https://github.com/Azure-Samples/active-directory-python-webapp-graphapi/blob/961608ada728af788097d3c0ce7f49b9e662f3c6/app.py#L49) we can be pretty confident that the token is legit because of the great work done on ADAL.

But it sounds like it would be a good practice / wouldn't hurt for an application to also validate the token at the JWT level after receiving it to help ensure someone didn't alter the response as per [these docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#validate-the-id_token)?

**Comment by rayluo** [comment]
Sure your app can do that, and sometimes you should. Personally I would think the JWT level validation would be necessary when you store the raw id_token in some untrusted storage, and later when you read it and use it, at that time you might want to validate it to make sure nobody tampers it in your storage. From ADAL Python's perspective, though, we already know the id_token is freshly returned from a trusted source, so ADAL Python has one less [attack vector](https://en.wikipedia.org/wiki/Vector_(malware)) to worry about.

**Comment by rayluo** [comment]
@boykoc et al, FYI: The above referenced link is an MSAL Python issue. We provide an already-validated id_token_claims out-of-box there.
