### ISSUE TITLE
Unexpected polling state invalid_client when getting token with device code.

### ISSUE THREAD

**Issue by TWXjm** [AzureAD/azure-activedirectory-library-for-python#175]
I'm following the sample code from here [1]  I keep getting the error below my user enters the code and authenticates his username/password.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dummy/keyvault-test/lib/python3.5/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/dummy/keyvault-test/lib/python3.5/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/dummy/keyvault-test/lib/python3.5/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/dummy/keyvault-test/lib/python3.5/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/dummy/keyvault-test/lib/python3.5/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state invalid_client
```

Any ideas what could be wrong?

[1] https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/device_code_sample.py#L53-L58

**Comment by rayluo** [comment]
Hi @TWXjm , did this error happen after a long time? Have you been able to complete a device code sign in interaction from a browser during those time? In case you haven't already known or done so, this is the typical interaction when using Device Flow (quoted from [a .Net sample app with more detailed explanation about the device flow](https://github.com/azure-samples/active-directory-dotnet-deviceprofile) but the concept and interaction are the same):

![Device Flow interaction](https://raw.githubusercontent.com/Azure-Samples/active-directory-dotnet-deviceprofile/master/ReadmeFiles/deviceCodeFlow.png)

**Comment by TWXjm** [comment]
Hi Ray,
Yes, I have read that page. And that is flow I'm following.

I get the error immediately after the user authenticates with its credentials. I should also mention that the resource I'm trying to reach is Key Vault. In order, the steps to reproduce the issue are:
1.- From a python interactive prompt, run this code [1] (All modules are already loaded). Where:
```
authority_url = 'https://login.microsoftonline.com/my_tenant_id'
RESOURCE =  'https://vault.azure.net'
clientid = my_client_id
```
2.- Open the URL https://microsoft.com/devicelogin in a browser.
3.- Enter the code E8B2DVT67
4.- Confirm the application's name, KV-TEST-APP is correct.
5.- Authenticate using the user's credentials.
6.- Get a message in browser saying "You have signed in to the KV-TEST-APP application on your device. You may now close this window."
7.- Get the error shown in my previous message in the python interactive prompt.

In my AD, the KV-TEST-APP has permissions to access Key Vault resources. 

[1] https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/sample/device_code_sample.py#L53-L58

**Comment by rayluo** [comment]
Quick question, what is the application type of your KV-TEST-APP? Is it "web app/api" or "native"? I believe currently ADAL Python provides Device Flow for native app only.

![image](https://user-images.githubusercontent.com/821550/47320874-905e1480-d607-11e8-89ad-1664aa40e431.png)

**Comment by TWXjm** [comment]
That was the problem. Mine was a web app. After changing it to Native (re-creating it), everything works. 
As a curiosity, is there a compound identity authentication model supported ADAL Python that works for Web Apps?

Thank you for the help.

**Comment by rayluo** [comment]
@TWXjm Glad to know that changing the app type to `Native` allows you to use Device Flow. Historically ADAL Python does not support using Devide Flow in a web app. We could revisit this, though.

Meanwhile, if you want to work on a web app, you can choose to use Authorization Code flow. [ADAL Python accepts a client_secret parameter for that flow, as demonstrated in this sample](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.0/sample/website_sample.py#L118).

PS: Since this thread already finishes a Q&A on Device Flow, I'm closing it. Feel free to start a new issue if you encounter some other problem. :-)

**Comment by DheerendraRathor** [comment]
@rayluo What is the reason for adding additional check in SDK for native client only? Also App registration preview creates only web app/Api apps. Adal sdk isn't working for them.

**Comment by rayluo** [comment]
@DheerendraRathor There is no real reason for a client side SDK to exclude web client. It is just that, historically this API has long been implemented and tested with native client only. Again, we could revisit this in future.

To answer your 2nd question, the App registration preview can still create Public (i.e. native) app.
![image](https://user-images.githubusercontent.com/821550/49104658-5a7a0480-f233-11e8-8693-66eeb0b974ed.png)

**Comment by DheerendraRathor** [comment]
That's not what I'm seeing. 
I created an app with Public client redirect URI in the way you described with redirect URI as "urn:ietf:wg:oauth:2.0:oob". 
<img width="835" alt="screenshot 2018-11-28 at 12 54 42 am" src="https://user-images.githubusercontent.com/4997888/49106240-a6b35c00-f2a8-11e8-9d8f-1548419dc809.png">

But when you see apps in Non-Preview portal it comes as "Web app/API" app. 

<img width="1126" alt="screenshot 2018-11-28 at 12 55 34 am" src="https://user-images.githubusercontent.com/4997888/49106340-ebd78e00-f2a8-11e8-9a89-51e99ebd4b53.png">

Also, I firmly believe that there shouldn't be any such restriction to exclude web client from device code auth flow. If `adal` won't do it, someone probably will build another library to use device code flow. In the end all of these are plain REST APIs. And if these APIs are not imposing any restriction, I don't see any reason for clients to impose any artificial restriction.

**Comment by DheerendraRathor** [comment]
Also adding on top of it, to make "Native" client from preview portal, only way I could find was to update manifest and set `"allowPublicClient": true,` which by default is set to `null`.

**Comment by Lucia-Marcos** [comment]
@DheerendraRathor I had tried 12 hours to solve this ... thank you very much for your comment!
