### ISSUE TITLE
Get Token request returned http error: 500

### ISSUE THREAD

**Issue by Saravanakumar-dotsolved** [AzureAD/azure-activedirectory-library-for-python#18]
When I try to get the token using the following credentials I get the error.

RESOURCE_URI = 'https://XXXXXXX.api.crm.dynamics.com'
USERNAME = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
PASSWORD = 'XXXXX'
#AUTHORIZATION_URL = 'https://login.microsoftonline.com/07522de8-b828-4759-8673-f0622ae2012c'
AUTHORIZATION_URL = '//login.windows.net/ABCDEFGH-1234-ABCD-1234-ABCDEFGHIJKL'

token_response = adal.acquire_token_with_username_password(
        AUTHORIZATION_URL,
        USERNAME,
        PASSWORD,
        resource=RESOURCE_URI
    ) 

and the error I get is 

Exception: Error:Error:Error:Get Token request returned http error: 500 and server response: {"error":"server_error","error_description":"AADSTS90036: Directory Proxy Client encountered an internal error.\r\nTrace ID: 1f39ca43-a156-4a2c-a6f6-c3281d28db52\r\nCorrelation ID: fcf8ceff-f18e-4f91-9197-ec93101d527c\r\nTimestamp: 2016-06-03 09:09:05Z","error_codes":[90036],"timestamp":"2016-06-03 09:09:05Z","trace_id":"1f39ca43-a156-4a2c-a6f6-c3281d28db52","correlation_id":"fcf8ceff-f18e-4f91-9197-ec93101d527c"} token_response:{u'timestamp': u'2016-06-03 09:09:05Z', u'trace_id': u'1f39ca43-a156-4a2c-a6f6-c3281d28db52', u'correlation_id': u'fcf8ceff-f18e-4f91-9197-ec93101d527c', u'error_description': u'AADSTS90036: Directory Proxy Client encountered an internal error.\r\nTrace ID: 1f39ca43-a156-4a2c-a6f6-c3281d28db52\r\nCorrelation ID: fcf8ceff-f18e-4f91-9197-ec93101d527c\r\nTimestamp: 2016-06-03 09:09:05Z', u'error': u'server_error', u'error_codes': [90036]} token_response:None token_response:None

**Comment by yugangw-msft** [comment]
Is `'//login.windows.net/ABCDEFGH-1234-ABCD-1234-ABCDEFGHIJKL'` a valid url?
Also to isolate the issue,could you try other azure common resource such as `00000002-0000-0000-c000-000000000000`

**Comment by yugangw-msft** [comment]
please reopen with more details

**Comment by angey** [comment]
I got the similar error :-)
