### ISSUE TITLE
Not able to access users messages using ADAL

### ISSUE THREAD

**Issue by afizs** [AzureAD/azure-activedirectory-library-for-python#180]
Hello Team, 

I am not able to list other users messages(outlook) programmatically whereas using graph API explorer I am able to list other user emails. 

Here is app setting: 
<img width="938" alt="screenshot 2018-10-30 at 10 58 36 am" src="https://user-images.githubusercontent.com/5618143/47697955-51494800-dc33-11e8-93a9-62806d695a8e.png">

**Comment by rayluo** [comment]
Hi Afiz, thanks for your interests in using this product. Would you mind share us your code snippet i.e. which function(s) you are using, and what exact error message/exception trace did you observe? Basically, we would like to be able to reproduce this case for the investigation. Thanks!

**Comment by afizs** [comment]
Here is the code snippet: I have created app with admin account and added another test user as owner. using the below code I am only able to list emails of test user and for all other users I am getting access denied error. As I mentioned in my previous comment I am able to list other user emails using graph api explorer.  Any help would be greatly appreciated. 
```
from adal import AuthenticationContext
from os import path
import json
import requests

with open(credentialFile) as f: 
            ms_cred = json.load(f)
            mscontext = AuthenticationContext(
                ms_cred['AUTHORITY_URL'], api_version=ms_cred['API_VERSION'])
token = mscontext.acquire_token_with_username_password(
                ms_cred["RESOURCE"], ms_cred["USER_NAME"], ms_cred["PASSWORD"], ms_cred["CLIENT_ID"])
            with open(self.tokenFile, 'w') as f:
                json.dump(token, f)

session = requests.Session()
session.headers.update({'Authorization': f'Bearer {token["accessToken"]}',
                         'SdkVersion': 'TEST SDK',
                         'x-client-SKU': 'TEST Client'})

for user in users_list: #users_list has all the users email 
            try:
                endpoint = "users/{1}/messages?$search={0}".format(
                    query, user)
                print(">> search started for <<<{0}>>> mail box".format(
                    user))
                response = session.get(api_endpoint(endpoint))
                response = response.json()
                print(response)
            except:
                print("Not able to access")
```

**Comment by rayluo** [comment]
Well, I'm not an Outlook expert here, I don't know whether you are supposed to be allowed listing emails "for all **other** users". In the [Graph API explorer](https://developer.microsoft.com/en-us/graph/graph-explorer#) I see only queries for "my emails", "my inbox", "my something".

In the code snippet you provided, you successfully used one test user's credential to acquire a token, and then the token allows you to list emails for **that** user, but not someone else's email. That sounds very logical to me.

You still did not provide the error/exception, but, assuming the error message you see was from line `response = session.get(api_endpoint(endpoint))` and the error was an HTTP 401 error, I would suggest you get in contact with that graph api's team to understand how/whether that is supposed to work.

**Comment by navyasric** [comment]
@afizs As mentioned in above comment by rayluo, if you are getting 401 error when accessing the MS Graph API, please ensure that your app is registered with the right permissions to call the APIs. You can find the permissions you need for the different API calls on the [MS Graph documentation on permissions](https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference) or even using Graph Explorer you can check what permissions you are consenting to.

**Comment by rayluo** [comment]
@afizs , my guess is the resource/scope you used in your code snippet was different than what the Graph API explorer. And to confirm (or rule out) that possibility, we would need some expert from the Graph's side. So again, "I would suggest you get in contact with that graph api's team to understand how/whether that is supposed to work".
Perhaps you can repost your question [there](https://github.com/microsoftgraph/python-sample-auth)? They would probably give us more insight about the resources, or point you to the right direction? Before that, there is no much we can do here. CC: @dmahugh
