### ISSUE TITLE
How to perform search at orgnization level for OneDrive.

### ISSUE THREAD

**Issue by afizs** [AzureAD/azure-activedirectory-library-for-python#182]
Hello Team, 

Is there any way to perform search at org level? as of now I am making API for every Onedrive ID. Is there any alternative way to avoid multiple API calls and do search across all the OneDrives. I have seen in other Cloud storage like Google drive and Box they have enterprise option.

**Comment by rayluo** [comment]
This sounds like a question for OneDrive. If you happen to be using the [OneDrive Python SDK](https://github.com/OneDrive/onedrive-sdk-python) you can probably ask questions there, and close the question here. :-)
