### ISSUE TITLE
I can get an Access Token but receive an 401 error when I try and use it

### ISSUE THREAD

**Issue by SoapyD** [AzureAD/azure-activedirectory-library-for-python#195]
Hi! I'm trying to replicate an email reading system I've used elsewhere using Powershell but have hit an issue I can't resolve.

I've managed to use the acquire_token_with_client_credentials function to return an access token successfully but when I use it to try and return messages from my inbox I get a 401 error. I'm relatively new to rest apis but I know it means i'm failing authorisation.

Can anyone see any issues with my code snippet below? (id's and such have been removed). 

My business has recently started using microsoft two-factor authentication so I'm not sure if that has any bearing at all?

Thanks!

`def test3():

    import adal
    import requests

    #####GET THE ACCESS TOKEN

    authority_url = "https://login.microsoftonline.com/<TENANT ID>"  
    context = adal.AuthenticationContext(
        authority_url,
        validate_authority=True,
        api_version=None
    )

    token = context.acquire_token_with_client_credentials(
        resource='https://outlook.office.com/',
        client_id = <client_id>,
        client_secret = <client_secret>
    )

    access_token = token['accessToken']

   
    #####USE THE TOKEN TO REQUEST MESSAGE DATA FROM A SPECIFIC FOLDER

    folder_id = '<FOLDER_ID>'
    url = "https://outlook.office.com/api/v2.0/me/MailFolders/"+folder_id+"/messages"

    headers = {
        'Authorization': 'Bearer '.format(access_token)
    }

    
    r = requests.get(url, headers=headers)
    print(r)

test3()`

**Comment by rayluo** [comment]
Hi @SoapyD , thanks for your interest in using this library!

Your this line `'Bearer '.format(access_token)` was incompleted. Try `print(...)` that part of your snippet and you would find out. I'm closing this issue now. Feel free to create new issues if you hit any more things to ADAL Python.

**Comment by SoapyD** [comment]
Thanks Rayluo! I'll give it a try
