### ISSUE TITLE
Confusing error message on tenant on service principal login

### ISSUE THREAD

**Issue by dozer75** [AzureAD/azure-activedirectory-library-for-python#201]
Ref [this issue in azure-cli repo](https://github.com/Azure/azure-cli/issues/9115), the error message `The authority url must be of the format https://login.microsoftonline.com/your_tenant` is wrong, the correct error message should specify that your_tenant either is the guid or the domain name, and how to find it.

How to reproduce:
- Use Azure CLI
- log in using `az login --service-principal --username APP_ID --password SECRET --tenant SOME_BOGUS_TENANT`

**Comment by rayluo** [comment]
Commended in [that azure-cli issue](https://github.com/Azure/azure-cli/issues/9115#issuecomment-484690865).
