### ISSUE TITLE
Spelling mistake: auhtorization

### ISSUE THREAD

**Issue by lochyw** [AzureAD/azure-activedirectory-library-for-python#203]
https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/authentication_context.py#L181-L183

Line 184

Just trying to help ;)

**Comment by rayluo** [comment]
Fixed. Just trying to say thank you here @lochyw . :-)

**Comment by lochyw** [comment]
Sorry for the reopen, just wanted to confirm: https://docs.microsoft.com/en-us/azure/active-directory/develop/
This says v2 i.e MSAL isn't available for python yet.
Am I understanding that it's finally available? Was doing some research last night into ADAL as it appeared to be my only option.

If what I understand you're saying is true, this is super exciting! :D

**Comment by rayluo** [comment]
@PylotLight 
Thanks for bringing this to our attention. It seems true that [that Quickstart page](https://docs.microsoft.com/en-us/azure/active-directory/develop/) you referring to, as well as [its Authentication libraries v2 page](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries), did not mention MSAL Python. We will look into that. CC: @navyasric @jmprieur @henrik-me

Nonetheless, [MSAL Python is available as a preview library since last December](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases). It is not GA yet. That being said, historically ADAL Python had also been in preview/pre-release for 3 years, yet with production-level of support. So, I think you can keep being *super exciting*. :-)

**Comment by PylotLight** [comment]
Hey,
Please do point me to a better spot to ask.
But just having trouble understanding if MSAL does what I'm trying to do based on existing documentation.
My aim is to have a normal ADFS login with SSO for staff to have a login matching existing logins we have.
This seems to say MSAL doesn't support SSO/SAML yet: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison
But this one says I can use SSO/OAUTH for login?:
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-single-sign-on-portal
I'm also not sure which authorization flow I should be using to achieve this. [user+pw](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/username_password_sample.py) or [auth code](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample). (no example)
Struggling to piece together existing docs on my case to solve this one on my own.
Thanks.

**Comment by henrik-me** [comment]
MSAL Python doesn't yet support ADFS. When it does it will start by supporting ADFS 2019. Whether MSAL Python will support ADFS 2016 is yet to be defined. 
Before MSAL's can support ADFS there is a need for a server side update, at that moment [MSAL.NET] (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/834) will support ADFS 2019 and not long after Python will as well.
Which versions of ADFS are you looking for?
Note: ADAL support ADFS 2016.

**Comment by PylotLight** [comment]
@henrik-me thanks for the info.
Our Federation server is actually still on 2012 for a few months still.
So I should have a look back at adal lib for that?

**Comment by henrik-me** [comment]
@PylotLight : I would have liked you to stay on MSAL and consider ADFS 2019. However prior versions of ADFS are currently only supported in ADAL (MSAL currently only talks to standards compliant IdP's, and before ADFS 2019 that is not the case with ADFS). We are still considering options for supporting ADFS 2016, however I don't believe we will be supporting ADFS 2012 any time soon.

**Comment by rayluo** [comment]
@PylotLight Glad to hear that you are already making progress! (Henrik is very knowledgeable on this topic too, and he gave you idea of our [MSAL Python Roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Roadmap).)

Regarding to your earlier comment "auth code flow ... no example". Actually we are already working on [an auth code sample for MSAL Python](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/40) recently.

Back to your topic. You said you got it working with ADAL? Great! Are you using the username password flow? Is there anything that once confused you, and then you would want us to emphasize in our sample/wiki? Please [open a new issue here](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/new) for that one.
