### ISSUE TITLE
Replace "login.windows.net" with "login.microsoftonline.com" in the authority host list

### ISSUE THREAD

**Issue by ericsuhong** [AzureAD/azure-activedirectory-library-for-python#224]
In here: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/2a1c7ffabda0d79548533434db0cc9bbae6eefcf/adal/constants.py#L211

ADAL is still defaulting to "login.windows.net".

MSAL has removed this endpoint long time ago, and is using "login.microsoftonline.com" as a default instead: https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/6bade9faf7c832a47b13c8ac3eeba75f4084190f/msal/authority.py#L13

Can we replace "login.windows.net" with "login.microsoftonline.com" in ADAL to be consistent with MSAL as well?

**Comment by rayluo** [comment]
Hi @sukhong , nice to meet you, another vim user. :-)

Back then, the `login.microsoftonline.com` and `login.windows.net` were supposed to be alias of each other, without any tangible behavior difference. Is it not the case anymore? Did you observe some different behavior, that causes you to create this ticket?

By the way, what project are you working on? Can it be migrated to MSAL? :-)

**Comment by sukhong** [comment]
Hi, @rayluo .

For my scenario, we are using Azure CLI. Azure CLI is using ADAL, and we are having some problem because it is trying to call "login.windows.net" for metadata instance endpoint.

I cannot leave the details here, I will ping you directly on Teams regarding the problem we are seeing.

**Comment by rayluo** [comment]
Discussed with Sukhong offline. Azure CLI is in the progress of migrating to MSAL. For other topics, Sukhong will switch to an email conversation.

**Comment by henrik-me** [comment]
@rayluo as discussed, we are progressing with this fix asap.

**Comment by kaitree** [comment]
> Hi @sukhong , nice to meet you, another vim user. :-)
> 
> 
> 
> Back then, the `login.microsoftonline.com` and `login.windows.net` were supposed to be alias of each other, without any tangible behavior difference. Is it not the case anymore? Did you observe some different behavior, that causes you to create this ticket?
> 
> 
> 
> By the way, what project are you working on? Can it be migrated to MSAL? :-)

Good to know these two url are alias:)

**Comment by rayluo** [comment]
They are aliases of each other, but the new apps should use `login.microsoftonline.com` instead of the other one.

Besides, @kaitree , if you are still reading the ADAL Python issues and docs, you are doing it wrong. :-)  Your existing [ADAL Python-powered projects shall migrate to MSAL Python](https://learn.microsoft.com/en-us/azure/active-directory/develop/migrate-python-adal-msal), and your new projects should just begin with MSAL Python.
