### ISSUE TITLE
Somehow update ADAL's docs in docs.microsoft.com to mention MSAL

### ISSUE THREAD

**Issue by rayluo** [AzureAD/azure-activedirectory-library-for-python#236]
Currently, customer who comes from [this page](https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory/client?view=azure-python) would NOT know we recommend using MSAL over ADAL.

Action items:

* Figure out how and how often those docs pages are updated, and then we will know where/how to update our docs there.
* Update the docs.

**Comment by mmacy** [comment]
@rayluo @abhidnya13 Your one-stop shop for API reference onboarding can be found here:

https://review.docs.microsoft.com/en-us/help/onboard/reference?branch=master (**MSFT internal only**)

Take a look at that to see if you have all the prerequisites complete, the onboarding form that it links to (the blue button), and let me know if you have any questions. You can fill out the form and submit the request, and then I can help with updating the Overview page(s) to focus on MSAL and de-emphasize ADAL.

Let me know if you have any questions!

**Comment by abhidnya13** [comment]
Submitted a request using the onboarding form, Thanks @mmacy for your help.
