### ISSUE TITLE
Can't use username and password with v0.3.0

### ISSUE THREAD

**Issue by aarsan** [AzureAD/azure-activedirectory-library-for-python#27]
I just upgraded from 0.1.0 to 0.3.0. I was able to get a token like this:

    adal.acquire_token_with_username_password(
        'url',
        'username',
        'password
    )

Can I not use this library to get a token using username/password anymore?

**Comment by aarsan** [comment]
It looks I now have to add a client_id and also a resource. I am not sure what to put for those values but I am now getting 'the application name (appname) was not found in tenant named (tenantname)

**Comment by yugangw-msft** [comment]
Please check out the readme for the explanation and how to get a client_id.
This change is by-design

**Comment by dheena2u** [comment]
Even with Client ID Referenced , it is not working.

import adal

clientId = 'My Valid-Clie-ntID-xxxx-123456789101'
RESOURCE_URI = 'https://analysis.windows.net/powerbi/api' 
USERNAME = 'MyValidUserID@company.com' 
PASSWORD = 'MyPassword' 
AUTHORIZATION_URL = 'https://login.microsoftonline.com/common/oauth2/authorize'

context = adal.AuthenticationContext(AUTHORIZATION_URL) 
token_response = context.acquire_token_with_username_password(RESOURCE_URI,USERNAME,PASSWORD,clientId)
