### ISSUE TITLE
Does client cert auth work?

### ISSUE THREAD

**Issue by colemickens** [AzureAD/azure-activedirectory-library-for-python#3]
It's not obvious from the code/tests if it works at all.

**Comment by yugangw-msft** [comment]
@colemickens, the fix is in the dev branch already. For samples you can check out [my fork](https://github.com/yugangw-msft/azure-activedirectory-library-for-python/blob/final/sample/client_credentials_sample.py) which will be integrated soon

**Comment by yugangw-msft** [comment]
PR #7 fix it
