### ISSUE TITLE
Add API that allows apps to report app name and version for telemetry.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-python#30]
It would be helpful to be able to identify which apps have which version of ADAL so that we can identify apps that should be updated.

Do not implement this until we have agreement on the shape of the public API changes.

**Comment by rayluo** [comment]
Hi @RandalliLama , 3 and a half year later, I'm now pleased to say this feature has just been [picked up by MSAL Python here](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/136). Finally. :-)

All future new features will happen on MSAL Python going forward.
