### ISSUE TITLE
Return id_token with get_token_with_authorization_code

### ISSUE THREAD

**Issue by jleaniz** [AzureAD/azure-activedirectory-library-for-python#32]
The get_token_with_authorization_code function should also return the id_token along with the access_token as described in https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-protocols-oauth-code/

If i'm not mistaken, currently, it only returns an access_token and refresh_token.

**Comment by yugangw-msft** [comment]
The id_token will be parsed and consolidated into the returned token entry. The code logic is [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/master/adal/oauth2_client.py#L200) , for you reference
Feel free to reactivate if you see different behavior
