### ISSUE TITLE
Whats worng with this code to acquire a token

### ISSUE THREAD

**Issue by dheena2u** [AzureAD/azure-activedirectory-library-for-python#36]
import adal

clientId = 'My Valid-Clie-ntID-xxxx-123456789101'
RESOURCE_URI = 'https://analysis.windows.net/powerbi/api' 
USERNAME = 'MyValidUserID@company.com' 
PASSWORD = 'MyPassword' 
AUTHORIZATION_URL = 'https://login.microsoftonline.com/common/oauth2/authorize'

context = adal.AuthenticationContext(AUTHORIZATION_URL) 
token_response = context.acquire_token_with_username_password(RESOURCE_URI,USERNAME,PASSWORD,clientId)

**Comment by yugangw-msft** [comment]
`AUTHORIZATION_URL` is wrong.
Checkout the sample of at [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/master/sample/refresh_token_sample.py)

**Comment by dheena2u** [comment]
Hi Yugangw. I was able to overcome the original issue. Thank you very much.
Now I get this new error.
How do I overcome this interactive issue that is being reported?

``"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'My Valid-Clie-ntID-xxxx-123456789101'. Send an interactive authorization request for this user and resource.
``

**Comment by yugangw-msft** [comment]
The error is right. The application has not been consented to access your tenant.  Could you first try the [interactive flow](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/master/sample/device_code_sample.py) sample, in the browser you should be asked to consent, go with yes, and that should get all configured.
