### ISSUE TITLE
Installation should work in a clean environment

### ISSUE THREAD

**Issue by cdonati** [AzureAD/azure-activedirectory-library-for-python#46]
https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/39 changed the setup script so that several of the dependencies are required _before_ running `python setup.py install`. Trying to install in a clean virtualenv does not work.

**Comment by rayluo** [comment]
I got what you mean. We can optimize it in next release. Meanwhile, you can use `pip install adal` to install it without any problem, which is typically a preferred approach, easier than installing from source code. Or if you have any special reason that prevents you from doing `pip install`, please let us know the whole picture.

**Comment by cdonati** [comment]
It becomes an issue when another package specifies this one as a dependency. Even if there's not a use case for installing this package from source, users of downstream packages may be used to the `python setup.py install` convention when installing from source.

**Comment by yugangw-msft** [comment]
So put back the version string in `__init__.py`, and let `setup.py` to open the file and find the version?

**Comment by rayluo** [comment]
Yea that is pretty much what I plan to do. A prototype is described [here](http://stackoverflow.com/a/39671214/728675). I can send a PR soon.

**Comment by cdonati** [comment]
Thanks for the speedy response! I appreciate the fix. :+1:
