### ISSUE TITLE
Using username/password, bad URL matching pattern

### ISSUE THREAD

**Issue by lmazuel** [AzureAD/azure-activedirectory-library-for-python#60]
Hi @yugangw-msft,

Look at this:
```python
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidAuthenticationTokenAudience
Message: The access token has been obtained from wrong audience or resource 'https://management.core.windows.net'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'.
```

Why are you so nervous to also include the forward slash?

This raises also the question, what about connecting to not public azure?

**Comment by yugangw-msft** [comment]
@lmazuel, 
This is an error from ARM service.
Adal is a general purpose library, not just for authenticating with azure ad. It also work with adfs on-prem, and any other web-api based resources; hence we don't polish the url

**Comment by lmazuel** [comment]
@yugangw-msft 
You mean, this message does not come from the ADAL code?

**Comment by yugangw-msft** [comment]
@lmazuel , that is correct, it is a server error
