### ISSUE TITLE
authentication_context.py:88: DeprecationWarning

### ISSUE THREAD

**Issue by gbowerman** [AzureAD/azure-activedirectory-library-for-python#67]
Why am I getting an authentication_context.py:88: DeprecationWarning even when calling: 
context = adal.AuthenticationContext((authentication_endpoint + tenant_id, **api_version=None**))

**Comment by rayluo** [comment]
At the first quick glance, your code snippet contains an extra pair of parenthesis. Could that be the reason?

**Comment by Walk4Muscle** [comment]
@gbowerman , Have you checked the adal lib version you are using?

**Comment by gbowerman** [comment]
@Walk4Muscle thanks, I'll close this. I was using the latest adal library and it was resolved when I changed my code to:
context = adal.AuthenticationContext(authentication_endpoint + tenant_id, api_version = None)
