### ISSUE TITLE
Authorization failed with MSA and password

### ISSUE THREAD

**Issue by options** [AzureAD/azure-activedirectory-library-for-python#69]
I'd like to share that a problem that can't be authorized using id(MSA) and password. In fact, It's a bit ambiguous to tell this to Azure Cli project or to ADAL python project. But since the Azure cli is build on ADAL python. I think it's more appropriate to write here. 
It's horrible for the customer couldn't login with own id (MSA) and password when trying to access Azure CLI. This is very natural with PowerShell
Becuase of that. I have tried to drill down what's going on. and I share it.

I really hope that below information could be helpful to fix this problem(?), anyway.
Additionally, some of respose of it, "not recommended", I guess the most of people might want to know why is not recommended. just "not recommended" is not enough to answer.

BTW, When I tried to login with MSA and password, error call stack is like below.

Mex._select_username_password_polices in mex line 134     Python
Mex.**_parse** in mex line 251          Python
Mex.discover in mex line 104       Python
TokenRequest.**_get_token_username_password_federated** in token_request line 238     Python
TokenRequest.get_token_with_username_password in token_request line 286     Python
token_func in AuthenticationContext.acquire_token_with_username_password in authentication_context line 143     Python
AuthenticationContext._acquire_token in authentication_context line 109       Python
AuthenticationContext.acquire_token_with_username_password in authentication_context line 145     Python
SubscriptionFinder.find_from_user_account in _profile line 333           Python
Profile.find_subscriptions_on_login in _profile line 121           Python
login in custom line 70    Python
_execute_command in create_command in __init__ line 333    Python
Application.execute in application line 157  Python
main in main line 37       Python
__main__ module line 23   Python

I found that exception originate is select_username_password_polices() function

def _select_username_password_polices(self, xpath):
        policies = {}
        // xpath = 'wsp:Policy/wsp:ExactlyOne/wsp:All/sp2005:SignedSupportingTokens/wsp:Policy/sp2005:UsernameToken/wsp:Policy/sp2005:WssUsernameToken10'
        username_token_nodes = xmlutil.xpath_find(self._dom, xpath)           **// couln't find user token** information
        if not username_token_nodes:
            self._log.warn("No username token policy nodes found.")
            return
...

This is below log information as i tested

Command arguments ['login', '-u', 'himskim@msn.com']
Loading all installed modules as module with name 'login' not found.
Installed command modules ['acr', 'acs', 'appservice', 'cloud', 'component', 'configure', 'container', 'context', 'feedback', 'network', 'profile', 'resource', 'role', 'storage', 'vm']
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x03E176F0>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x03E176F0>
...
Loaded all modules in 6.903 seconds. (note: there's always an overhead with the first module loaded)
Application event 'CommandTable.Loaded' with event data {'command_table': OrderedDict([('provider register', <azure.cli.core.commands.CliCommand object at 0x04D3E5D0>), ('network traffic-manager endpoint list', <azure.cli.core.commands.CliCommand object at 0x04CFEFF0>), ('network application-gateway ssl-cert list', <azure.cli.core.commands.CliCommand object at 0x0446C850>), ('network vnet-gateway reset', <azure.cli.core.commands.CliCommand object at 0x04CE70F0>), ('network vnet peering update', <azure.cli.core.commands.CliCommand object at 0x04 [...]
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': OrderedDict([('provider register', <azure.cli.core.commands.CliCommand object at 0x04D3E5D0>), ('network traffic-manager endpoint list', <azure.cli.core.commands.CliCommand object at 0x04CFEFF0>), ('network application-gateway ssl-cert list', <azure.cli.core.commands.CliCommand object at 0x0446C850>), ('network vnet-gateway reset', <azure.cli.core.commands.CliCommand object at 0x04CE70F0>), ('network vnet peering update', <azure.cli.core.commands.CliCommand object at 0x04 [...]
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='login', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az login', usage=None, description='Log in to access Azure subscriptions', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], command='login', func=<function create_command.<locals>._execute_command at 0x04D2B1E0>, password=None, service_principal=None, te [...]
Password:
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - Authority:Performing instance discovery: https://login.microsoftonline.com/common
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - Authority:Performing static instance discovery
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - Authority:Authority validated via static instance discovery
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - TokenRequest:Acquiring token with username password.
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - OAuth2Client:finding with query: {"userId": "himskim@msn.com", "_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46"}
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - OAuth2Client:Looking for potential cache entries:
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - OAuth2Client:{"userId": "himskim@msn.com", "_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46"}
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - OAuth2Client:Found 0 potential entries.
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm:Performing user realm discovery at: https://login.microsoftonline.com/common/UserRealm/himskim%40msn.com?api-version=1.0
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
requests.packages.urllib3.connectionpool : https://login.microsoftonline.com:443 "GET /common/UserRealm/himskim%40msn.com?api-version=1.0 HTTP/1.1" 200 363
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm:User Realm Discovery Server returned this correlation_id: 532b43b3-a5b1-4443-a0a0-f3a563efc576
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm:Discovery response:
{"ver":"1.0","account_type":"Federated","domain_name":"live.com","federation_protocol":"WSTrust","federation_metadata_url":"https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml","federation_active_auth_url":"https://login.live.com/rst2.srf","cloud_instance_name":"microsoftonline.com","cloud_audience_urn":"urn:federation:MicrosoftOnline"}
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm:UserRealm response:
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm: AccountType:             federated
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm: FederationProtocol:      wstrust
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm: FederationMetatdataUrl:  https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - UserRealm: FederationActiveAuthUrl: https://login.live.com/rst2.srf
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - TokenRequest:Acquiring token with username password for federated user
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - TokenRequest:Attempting mex at: https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - MEX:Mex created with url: https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - MEX:Retrieving mex at: https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): nexus.passport.com
requests.packages.urllib3.connectionpool : https://nexus.passport.com:443 "GET /FederationMetadata/2007-06/FederationMetadata.xml HTTP/1.1" 200 2980
adal-python : 532b43b3-a5b1-4443-a0a0-f3a563efc576 - MEX:No username token policy nodes found.

Thanks.
myung

**Comment by rayluo** [comment]
ADAL does not come with MSA account support. This is a new feature which we are working on.

**Comment by yugangw-msft** [comment]
@options, the account is federated. ADAL-Python only supports wstrust2005 or wstrust13. If you show the error trace to the onprem ADFS admin, they should understand what extra configuration they need to do.

**Comment by rayluo** [comment]
We recently encountered a similar issue in our another authentication library, MSAL Python. With our current understanding, we consider this is [NOT a feature that the underlying Identity service is going to support](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/33#issuecomment-481843088). So we are now also closing this issue here.
