### ISSUE TITLE
client cert auth failing

### ISSUE THREAD

**Issue by johnarnold** [AzureAD/azure-activedirectory-library-for-python#79]
Getting this error:

E           Failed: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Client assertion audience claim does not match Realm issuer.\r\nTrace ID: b3a77dbe-af3b-4545-8c2c-a76ab79c15ff\r\nCorrelation ID: 5018bf95-777c-448c-96ea-19e2532cbb48\r\nTimestamp: 2017-03-08 23:18:59Z","error_codes":[70002,50012],"timestamp":"2017-03-08 23:18:59Z","trace_id":"b3a77dbe-af3b-4545-8c2c-a76ab79c15ff","correlation_id":"5018bf95-777c-448c-96ea-19e2532cbb48"}

What does this error mean?

code looks like:
    
            key_contents = get_contents(key)
            thumbprint = kf.get_private_rsa_fingerprint(key)
            token_response = context.acquire_token_with_client_certificate(
                kusto_cluster,
                client_id,
                key_contents,
                thumbprint
            )

If I use similar params, but use client_secret, it works fine:

            token_response = context.acquire_token_with_client_credentials(
                kusto_cluster,
                client_id,
                client_secret)

**Comment by yugangw-msft** [comment]
@johnarnold, likely the service principal has not been consented to access `kusto_cluster`. Since you are not in a interactive flow, you can do it in azure portal

**Comment by rayluo** [comment]
@johnarnold Did the previous answer help you out? Let us know if you need more help.

**Comment by akrulwich** [comment]
@johnarnold Did you ever figure out what the cause of this error was?
