### ISSUE TITLE
Issue with authenticating to Dynamics 365 CRM

### ISSUE THREAD

**Issue by jnthnltz** [AzureAD/azure-activedirectory-library-for-python#80]
I am having issues authenticating to the Dynamics 365 CRM Web API via the Python ADAL library. Particularly, the acquire_token_with_username_password function. I can't seem to acquire an access token. Full error message below.

The only "wrinkle" in my configuration is that our Azure AD is federated with an on-prem AD. Also, authentication seems to work using a device code & interactive login via the acquire_token_with_device_code function. The problem is I am writing a console application that is intended to be non-interactive.

Has anyone else encountered this issue, or could otherwise explain how to resolve it?

> adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50008: SAML token is invalid. AADSTS50006: The element with ID '_011236b3-e879-4bb5-b640-86577dda2a0a' was either unsigned or the signature was invalid.\r\nTrace ID: 7b0fbeae-5a37-42bd-af63-f1decf720926\r\nCorrelation ID: 3242f1a3-41be-49f3-ab2c-b643625b8d5b\r\nTimestamp: 2017-03-13 02:34:41Z","error_codes":[70002,50008,50006],"timestamp":"2017-03-13 02:34:41Z","trace_id":"7b0fbeae-5a37-42bd-af63-f1decf720926","correlation_id":"3242f1a3-41be-49f3-ab2c-b643625b8d5b"}

**Comment by rayluo** [comment]
We will need extra time to investigate this.

Meanwhile, that device code flow is actually the recommended way to do this. We really don't suggest to somehow keep the end user's username and password (in plaintext!) around and then authenticate non-interactively.

**Comment by jnthnltz** [comment]
Thank you for responding.   This app is meant to be non-interactive - i.e. it goes out and gets data from a third-party and then inserts it into Dynamics CRM.   This is meant to be something that occurs on a nightly schedule without requiring user intervention.  If you contact me privately I can give you more information into our use case and what we're trying to do.

**Comment by sonypop** [comment]
Hi @jnthnltz! Did you have any luck getting around this? I have the exact same use case as you and we are getting the same error... Did you end up using a different authentication flow?

**Comment by cesonsg** [comment]
I have the exact same error too. When I switch to .NET library the authentication with username and password works perfectly. Would be nice if anyone can help on this issue.

**Comment by rayluo** [comment]
We are yet to conclude this issue. However, we heard an individual case before, suggesting that switching from Python 2.7.10 to Python 3.6 would be a workaround. Will that mitigate your environment?

**Comment by cesonsg** [comment]
@rayluo Thanks for the suggestion. I tried switching the virtual env from Python 2.7.8 to 3.6 today but the error remains the same:

> adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50008: SAML token is invalid. AADSTS50006: The element with ID '_60165a78-a85e-4f73-97a9-4f9261d161a1' was either unsigned or the signature was invalid.\r\nTrace ID: 0cd5c2a1-cf6d-462d-9109-c0b30a811500\r\nCorrelation ID: 21ec8f49-a668-49b0-a268-f1b84921340b\r\nTimestamp: 2017-10-20 15:44:55Z","error_codes":[70002,50008,50006],"timestamp":"2017-10-20 15:44:55Z","trace_id":"0cd5c2a1-cf6d-462d-9109-c0b30a811500","correlation_id":"21ec8f49-a668-49b0-a268-f1b84921340b"}

One thing to note is that the Client Id is referring to an Enterprise Application in the Azure AD. My attempt with .NET library using authContext.AcquireTokenAsync with UserCredential (same username and password) works without issue.

**Comment by rayluo** [comment]
Hi @jnthnltz @sonypop @cesonsg , thanks for your patience, we recently made some progress on this one. Please take a look and ideally also test out the upcoming PR #120
