### ISSUE TITLE
Do extra parameters from the STS get surfaced to developer?

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/azure-activedirectory-library-for-python#85]
In the case the STS returns back an error with an extra parameter, is it accessible to the developer. For instance:

```
error=interaction_required

error_description=AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '<Web API App/Client ID>'.

claims={"access_token":{"polids":{"essential":true,"Values":["<GUID>"]}}}
```

**Comment by rayluo** [comment]
Looks like the same as this [feature request in MSAL dotnet](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/57). I'll take a look.

**Comment by danieldobalian** [comment]
Yup, this scenario applies to v1 and v2.

**Comment by danieldobalian** [comment]
Closed item because ADAL python does not support on-behalf-of flow. Error should still be bubbled up in other error cases, so the change is still relevant.
